//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionMetric
    {
        public int MetricID { get; set; }
        public int LineID { get; set; }
        public System.DateTime MetricDate { get; set; }
        public Nullable<decimal> ProductionRate { get; set; }
        public Nullable<decimal> Efficiency { get; set; }
        public Nullable<decimal> QualityRate { get; set; }
        public Nullable<decimal> Downtime { get; set; }
    
        public virtual ProductionLine ProductionLine { get; set; }
    }
}
