//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMAD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionTrend
    {
        public int TrendID { get; set; }
        public int LineID { get; set; }
        public System.DateTime TrendDate { get; set; }
        public Nullable<decimal> AverageProductionRate { get; set; }
        public Nullable<decimal> AverageEfficiency { get; set; }
        public Nullable<decimal> AverageQualityRate { get; set; }
    
        public virtual ProductionLine ProductionLine { get; set; }
    }
}
